config/routes.rb
Rails.application.routes.draw do
  resources :comments
  get 'pages/about'

  get 'pages/contact'

  get 'pages/resources'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :categories
  get 'categories/index'

  get 'categories/edit'

  get 'categories/new'

  get 'categories/show'

  get 'home/index'
  resources :posts
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/resources', to: 'pages#resources'

  root 'home#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post

  validates_presence_of :name
  validates_length_of :name, within: 2..20
  validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
#attr_accessor :title, :body , :category_id, :author_id
belongs_to :category
belongs_to :admin_user
has_many :comments, dependent: :destroy 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  #helper_method :all_categories
  before_action :site_search
  def site_search

    @q = Post.search(params[:q])
    @search_result = @q.result(distinct: true)

  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @title = @category.name
    @posts = @category.posts
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/comments_controller.rb
class CommentsController < InheritedResources::Base

  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      flash[:notice] = "Comentário adicionado com sucesso"    
    else
      flash[:notice] = "Erro ao adicionar comentário"
    end
    redirect_to @comment.post
  end

  private

    def comment_params
      params.require(:comment).permit(:name, :email, :body, :post_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @q = Post.search(params[:q])
    @posts = @q.result(distinct: true)
  end

  def show
    @post = Post.find(params[:id])
    @user = AdminUser.all
    @new_comment = Comment.new(post: @post)
    @comments = @post.comments
  end

  def new
    @post = Post.new
    @category = Category.all
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path, notice: "Post Criado"
    else
        render "new"
    end

  end

  def edit
    @post = Post.find(params[:id])
    @category = Category.all
  end

  def update
    @post = Post.find(params[:id])

    if @post.update_attributes(post_params)
      redirect_to post_path, notice: "Post Atualizado"
    else
      render "edit"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path , notice: "Post deletado"
  end

  private
  def post_params
    params.require(:post).permit(:title, :body, :category_id, :author_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def all_categories
    @categories = Category.all
  end

  def all_posts
    @posts = Post.all
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categorias</h1>

<ul>
<% @categories.each do |category| %>
    <%= link_to category.name, category %><br>
<% end %>
</ul>

<br>

app/views/categories/show.html.erb
<div class="post">
<p id="notice"><%= notice %></p>

<p>
  <h1><%= @category.name %></h1>
</p>
</div>

<% @posts.each do |post| %>
<div class="post">
  <h3><%= link_to post.title, post %></h3>
  <p> <%= post.body %> </p>
  </div>
<% end %>
<% if @posts.empty? %>
  <p> Não há posts nessa categoria </p>
<% end %>

app/views/home/index.html.erb
<% @posts.each do |post| %>
<div class="post">
<h2 class="title"><%= link_to post.title,post %></h2>
<div class="entry">
  <p> <%= post.body %> </p>
</div>
<small><%= post.created_at.strftime("%d %b %Y")%></small><br>
  Criado por <%= post.admin_user.name %>
<div class="byline">
							<p class="links"> <%= link_to "Leia Mais",post %> </p>
						</div>
</div>

<% end %>

app/views/layouts/application.html.erb
<%= render "partials/header" %>
	<div id="page">
		<div id="page-bgtop">
			<div id="page-bgbtm">
				<div id="content">
					<%= yield %>
					<div style="clear: both;">&nbsp;</div>
				</div>
				<!-- end #content -->

        <%= render 'partials/sidebar' %>

        <div style="clear: both;">&nbsp;</div>
			</div>
		</div>
	</div>
	<!-- end #page -->
	<div id="footer">
		<p>&copy; 2013, My Ruby Blog - Sample Project</p>
	</div>
</div>
<!-- end #footer -->

</body>
</html>

app/views/pages/about.html.erb
<div class="post">
<h1>Sobre o Suco de Uva</h1>
<p>
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tempus, diam vel dictum mollis, mi enim suscipit mi, mattis blandit nunc lorem quis enim. Praesent fringilla enim nibh, non viverra augue bibendum eget. Nunc ut cursus arcu. Curabitur nec est sit amet enim vulputate eleifend. Aliquam sodales dignissim justo, eget dignissim urna consequat quis. Aliquam feugiat feugiat sem, a cursus lorem porttitor ac. Aenean facilisis molestie fringilla. Duis quis tellus sagittis, auctor metus sit amet, maximus risus. Nulla fringilla sem et tortor mattis, id cursus est fringilla. Praesent fringilla mi non dolor accumsan, a auctor ante porttitor. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Curabitur dui lectus, malesuada quis ante in, lobortis sodales tellus. Phasellus sed sem luctus, eleifend enim consectetur, pellentesque augue. Duis luctus neque sapien, dapibus euismod ligula suscipit in. Vestibulum gravida ultrices cursus.

  Quisque sed sollicitudin justo. Suspendisse fermentum nisl eget turpis mattis, a interdum orci fermentum. Donec gravida vulputate ipsum vitae vulputate. Quisque at nunc sit amet nisi scelerisque varius non ut nisi. Duis sodales, mauris ut dictum aliquam, elit neque mattis diam, in ullamcorper ipsum lorem quis felis. Pellentesque ut lobortis lorem, sit amet pellentesque nisi. Phasellus nec erat elit.

  Phasellus iaculis neque in ante ullamcorper, nec tempor velit convallis. Ut ac ipsum tellus. Ut ullamcorper lacus neque, nec cursus enim viverra sed. Duis ullamcorper, elit eu sagittis congue, lectus nulla condimentum arcu, sed auctor magna urna a risus. Nunc quis dignissim felis. Etiam varius nisi ut turpis mollis, quis suscipit dui maximus. Integer non sagittis nulla.

  Vestibulum vel est elit. Aliquam erat volutpat. Proin vulputate, velit et interdum vulputate, augue quam pellentesque risus, malesuada finibus ex nunc at sem. Fusce molestie sem posuere convallis mattis. Aenean sed neque at dolor eleifend pharetra et non diam. Etiam venenatis volutpat nunc sed vulputate. Phasellus rhoncus varius urna, et gravida ligula tempus ac. Integer non nunc eu lectus ullamcorper iaculis. Integer euismod mi imperdiet erat congue luctus nec at tellus. Quisque tempor quam sed augue lobortis gravida. Donec cursus quam eget augue sollicitudin, at pharetra urna semper. Cras non lectus nibh. Nulla aliquet vel neque sed mollis. Donec volutpat nisi sit amet erat interdum consectetur. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras eleifend bibendum ex, sed aliquam massa luctus vitae.
</p>
</div>

app/views/pages/contact.html.erb
<div class='post'>
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</div>

app/views/pages/resources.html.erb
<div class='post'>
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>
</div>

app/views/partials/_comment.html.erb
<br />
<div class="comment">
  <i> <%=h comment.name %> : </i>
  <%= simple_format h(comment.body) %>
</div>

app/views/partials/_header.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog Suco de Uva</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link href="http://fonts.googleapis.com/css?family=Abel" rel="stylesheet" type="text/css" />

</head>
<body>


<% flash.each do |key,value| %>
  <p> <%= value %></p>
<% end %>


<div id="wrapper">
	<div id="header-wrapper">
		<div id="header">
			<div id="logo">
				<h1><a href="#">Suco de Uva</a></h1>
				<p>Learning Ruby on Rails</p>
			</div>
      <div id='menu'>
        <ul class="main-nav">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Sobre", about_path %></li>
          <li><%= link_to "Blog", posts_path %></li>
          <li><%= link_to "Contato", contact_path%></li>
          <li><%= link_to "Recursos", resources_path%></li>
        </ul>
      </div>
		</div>
	</div>
	<!-- end #header -->

app/views/partials/_sidebar.html.erb
<div id="sidebar">
  <ul>
    <li>
      <div id="search" >
        <%= search_form_for @q do |f| %>

          <%= f.search_field :title_or_body_contains %>

          <%= f.submit "Procurar" %>

      <% end %>
      </div>
      <div style="clear: both;">&nbsp;</div>
    </li>
    <li>
      <h2>Get The Framework</h2>
      <p>You can download Ruby and/or Ruby on Rails for free right now
                                                    <br />
                                                    <a style="color:#D93544;" href="http://rubyonrails.org/download" target="blank">GET IT NOW</a>
                                                </p>
    </li>
    <li>
      <h2>Categorias</h2>
      <ul>
        <% all_categories.each do |c| %>
          <li><%= link_to c.name, c %></li>
        <% end %>

      </ul>
    </li>
    <li>
      <h2>Blogroll</h2>
      <ul>
        <% all_posts.each do |p| %>
          <li><%= link_to p.title, p %></li>
        <% end %>
      </ul>
    </li>

  </ul>
</div>
<!-- end #sidebar -->

app/views/posts/index.html.erb
<% @posts.each do |post| %>
<div class="post">
<h2 class="title"><%= link_to post.title,post %></h2>
<div class="entry">
  <p> <%= post.body %> </p>
</div>
<small><%= post.created_at.strftime("%d %b %Y")%></small><br>
  Criado por <%= post.admin_user.name %>
<div class="byline">
							<p class="links"> <%= link_to "Leia Mais",post %> </p>
						</div>
</div>

<% end %>

app/views/posts/show.html.erb
<div class="post">
<h3><%= @post.title %></h3>
<p> <%= @post.body %> </p>
<small><%= @post.created_at.strftime("%d %b %Y")%></small>
<p>
  Criado por <%= @post.admin_user.name %>
</p>
<p> Categoria: <%= link_to @post.category.name, @post.category%> </p>
<p> <%= link_to "Voltar", posts_path %> </p>
<h3> Comente Aqui</h3>
<%= form_for(@new_comment) do |f| %>

  <%= f.hidden_field :post_id %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label "Comentário" %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= render partial: 'partials/comment', collection: @comments %>
</div>